
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: teste-unixerp_development

test:
  <<: *default
  database: teste-unixerp_test

production:
  <<: *default
  database: teste-unixerp_production
